---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-local-pv
  namespace: database
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/admin/database_home