---
apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-nginx-conf
  namespace: web
data:
  nginx.conf: |
    worker_processes  1;
    events { worker_connections  1024; }
    http {
      include       mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name _;
        # Serve the generated index.html from /usr/share/nginx/html
        location / {
          root   /usr/share/nginx/html;
          index  index.html;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      # Shared volume where initContainer writes index.html and NGINX serves it
      volumes:
        - name: site
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: web-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      initContainers:
        - name: init-page
          image: debian:12-slim
          command:
            - /bin/bash
            - -c
            - |
              set -eu
              POD_NAME="$HOSTNAME"
              # Take the LAST 5 characters of the pod name:
              SUFFIX="${POD_NAME: -5}"

              cat >/site/index.html <<'HTML'
              <!doctype html>
              <html>
              <head><meta charset="utf-8"><title>NGINX Web</title></head>
              <body style="font-family: sans-serif">
                <h2>NGINX on Kubernetes</h2>
                <p><b>Pod IP:</b> __POD_IP__</p>
                <p><b>serving-host:</b> Host-__SUFFIX__</p>
              </body>
              </html>
              HTML

              # Inject runtime values (Pod IP + computed suffix)
              sed -i "s/__POD_IP__/${POD_IP}/g" /site/index.html
              sed -i "s/__SUFFIX__/${SUFFIX}/g" /site/index.html
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: site
              mountPath: /site
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            # Serve generated page
            - name: site
              mountPath: /usr/share/nginx/html
            # Use custom nginx.conf
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: web
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080